#!/bin/bash

mountdir="/media/usbbackup"
device="65552126-c194-4fa6-be5f-15b6cab9cf91"

lockfile="/var/run/usbbackup.lock"

sourceDir="/media/storage"
targetDir="/media/usbbackup/Storage"

email="ramon.kluijtmans@gmail.com"

beep_start() {
	# Starting beep
	beep -f 3000 -l 100 -r 2
}

beep_ok() {
	# Ok beep
	beep -f 3000 -l 100 -r 3 -n -f 3000 -l 500
}

beep_error() {
	# Error beep
	beep -f 2000 -l 1200 -r 3
}

# Exit if device does not exist
if [ -b $device ]
then
	echo "Found $device"
else
	echo "Cannot find $device"
	beep_error
	exit 1
fi

if ! [ -d $sourceDir ]
then
	echo "Cannot find $sourceDir"
	beep_error
	exit 1
fi

if ! lockfile -r 0 $lockfile; then
	echo "Script already syncing"
	beep_error
	exit 1
fi

beep_start

# Create mount directory if it does not already exist
[ -d $mountdir ] || (mkdir $mountdir && echo "Created mount directory")

# Mount drive if it is not already mounted
if [ $(/bin/mount | grep -c $mountdir) != 1 ]
then
	echo "Mounting drive with uuid $device..."
        /bin/mount -U $device $mountdir || exit 1
        echo "$device is now mounted to $mountdir"
else
        echo "$mountdir already mounted"
fi

# Rsync job
rsyncresult=`rsync -avh $sourceDir/ $targetDir`

echo "$rsyncresult" | mail -s "USB Backup" $email

# Sync changes
sync

# Unmount drive
echo "Unmounting $device..."
udisksctl unmount -b /dev/disk/by-uuid/$device

rm -f $lockfile
